package com.github.andregpereira.resilientshop.userapi.cross.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.text.MessageFormat;
import java.text.Normalizer;
import java.util.Optional;
import java.util.StringJoiner;
import java.util.function.Predicate;
import java.util.stream.Stream;

@Getter
@AllArgsConstructor
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum Paises {
    AFEGANISTAO("Afeganistão", "AFG", "+93"),
    ALBANIA("Albânia", "ALB", "+355"),
    ARGELIA("Argélia", "DZA", "+213"),
    ANDORRA("Andorra", "AND", "+376"),
    ANGOLA("Angola", "AGO", "+244"),
    ANTIGUA_E_BARBUDA("Antígua e Barbuda", "ATG", "+1-268"),
    ARGENTINA("Argentina", "ARG", "+54"),
    ARMENIA("Armênia", "ARM", "+374"),
    AUSTRALIA("Austrália", "AUS", "+61"),
    AUSTRIA("Áustria", "AUT", "+43"),
    AZERBAIJAO("Azerbaijão", "AZE", "+994"),
    BAHAMAS("Bahamas", "BHS", "+1-242"),
    BAHREIN("Bahrein", "BHR", "+973"),
    BANGLADESH("Bangladesh", "BGD", "+880"),
    BARBADOS("Barbados", "BRB", "+1-246"),
    BELARUS("Belarus", "BLR", "+375"),
    BELGICA("Bélgica", "BEL", "+32"),
    BELIZE("Belize", "BLZ", "+501"),
    BENIN("Benin", "BEN", "+229"),
    BUTAO("Butão", "BTN", "+975"),
    BOLIVIA("Bolívia", "BOL", "+591"),
    BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina", "BIH", "+387"),
    BOTSWANA("Botswana", "BWA", "+267"),
    BRASIL("Brasil", "BRA", "+55"),
    BRUNEI("Brunei", "BRN", "+673"),
    BULGARIA("Bulgária", "BGR", "+359"),
    BURKINA_FASO("Burkina Faso", "BFA", "+226"),
    BURUNDI("Burundi", "BDI", "+257"),
    CABO_VERDE("Cabo Verde", "CPV", "+238"),
    CAMBOJA("Camboja", "KHM", "+855"),
    CAMAROES("Camarões", "CMR", "+237"),
    CANADA("Canadá", "CAN", "+1"),
    CATAR("Catar", "QAT", "+974"),
    CAZAQUISTAO("Cazaquistão", "KAZ", "+7"),
    CHADE("Chade", "TCD", "+235"),
    CHILE("Chile", "CHL", "+56"),
    CHINA("China", "CHN", "+86"),
    CHIPRE("Chipre", "CYP", "+357"),
    COLOMBIA("Colômbia", "COL", "+57"),
    COMORES("Comores", "COM", "+269"),
    CONGO_BRAZZAVILLE("Congo - Brazzaville", "COG", "+242"),
    COREIA_DO_NORTE("Coreia do Norte", "PRK", "+850"),
    COREIA_DO_SUL("Coreia do Sul", "KOR", "+82"),
    COSTA_DO_MARFIM("Costa do Marfim", "CIV", "+225"),
    COSTA_RICA("Costa Rica", "CRI", "+506"),
    CROACIA("Croácia", "HRV", "+385"),
    CUBA("Cuba", "CUB", "+53"),
    DINAMARCA("Dinamarca", "DNK", "+45"),
    DJIBUTI("Djibuti", "DJI", "+253"),
    DOMINICA("Dominica", "DMA", "+1-767"),
    EGITO("Egito", "EGY", "+20"),
    EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos", "ARE", "+971"),
    EQUADOR("Equador", "ECU", "+593"),
    ERITREIA("Eritreia", "ERI", "+291"),
    ESCOCIA("Escócia", "GBR", "+44"),
    ESLOVAQUIA("Eslováquia", "SVK", "+421"),
    ESLOVENIA("Eslovênia", "SVN", "+386"),
    ESPANHA("Espanha", "ESP", "+34"),
    ESTADOS_UNIDOS("Estados Unidos", "USA", "+1"),
    ESTONIA("Estônia", "EST", "+372"),
    ESUATINI("Esuatini", "SWZ", "+268"),
    ETIOPIA("Etiópia", "ETH", "+251"),
    FIJI("Fiji", "FJI", "+679"),
    FILIPINAS("Filipinas", "PHL", "+63"),
    FINLANDIA("Finlândia", "FIN", "+358"),
    FRANCA("França", "FRA", "+33"),
    GABAO("Gabão", "GAB", "+241"),
    GAMBIA("Gâmbia", "GMB", "+220"),
    GANA("Gana", "GHA", "+233"),
    GEORGIA("Geórgia", "GEO", "+995"),
    GIBRALTAR("Gibraltar", "GIB", "+350"),
    GRANADA("Granada", "GRD", "+1-473"),
    GRECIA("Grécia", "GRC", "+30"),
    GUADALUPE("Guadalupe", "GLP", "+590"),
    GUATEMALA("Guatemala", "GTM", "+502"),
    GUIANA("Guiana", "GUY", "+592"),
    GUIANA_FRANCESA("Guiana Francesa", "GUF", "+594"),
    GUINE("Guiné", "GIN", "+224"),
    GUINE_EQUATORIAL("Guiné Equatorial", "GNQ", "+240"),
    GUINE_BISSAU("Guiné-Bissau", "GNB", "+245"),
    HAITI("Haiti", "HTI", "+509"),
    HOLANDA("Holanda", "NLD", "+31"),
    HONDURAS("Honduras", "HND", "+504"),
    HONG_KONG("Hong Kong", "HKG", "+852"),
    HUNGRIA("Hungria", "HUN", "+36"),
    IEMEN("Iêmen", "YEM", "+967"),
    INDIA("Índia", "IND", "+91"),
    INDONESIA("Indonésia", "IDN", "+62"),
    IRA("Irã", "IRN", "+98"),
    IRAQUE("Iraque", "IRQ", "+964"),
    IRLANDA("Irlanda", "IRL", "+353"),
    ISLANDIA("Islândia", "ISL", "+354"),
    ISRAEL("Israel", "ISR", "+972"),
    ITALIA("Itália", "ITA", "+39"),
    JAMAICA("Jamaica", "JAM", "+1-876"),
    JAPAO("Japão", "JPN", "+81"),
    JORDANIA("Jordânia", "JOR", "+962"),
    KUWAIT("Kuwait", "KWT", "+965"),
    LAOS("Laos", "LAO", "+856"),
    LESOTO("Lesoto", "LSO", "+266"),
    LETONIA("Letônia", "LVA", "+371"),
    LIBANO("Líbano", "LBN", "+961"),
    LIBERIA("Libéria", "LBR", "+231"),
    LIBIA("Líbia", "LBY", "+218"),
    LIECHTENSTEIN("Liechtenstein", "LIE", "+423"),
    LITUANIA("Lituânia", "LTU", "+370"),
    LUXEMBURGO("Luxemburgo", "LUX", "+352"),
    MACAU("Macau", "MAC", "+853"),
    MACEDONIA("Macedônia", "MKD", "+389"),
    MADAGASCAR("Madagascar", "MDG", "+261"),
    MALASIA("Malásia", "MYS", "+60"),
    MALAWI("Malawi", "MWI", "+265"),
    MALDIVAS("Maldivas", "MDV", "+960"),
    MALI("Mali", "MLI", "+223"),
    MALTA("Malta", "MLT", "+356"),
    MARROCOS("Marrocos", "MAR", "+212"),
    MARTINICA("Martinica", "MTQ", "+596"),
    MAURICIA("Maurícia", "MUS", "+230"),
    MAURITANIA("Mauritânia", "MRT", "+222"),
    MEXICO("México", "MEX", "+52"),
    MOCAMBIQUE("Moçambique", "MOZ", "+258"),
    MOLDOVA("Moldova", "MDA", "+373"),
    MONACO("Mônaco", "MCO", "+377"),
    MONGOLIA("Mongólia", "MNG", "+976"),
    MONTENEGRO("Montenegro", "MNE", "+382"),
    MYANMAR("Myanmar", "MMR", "+95"),
    NAMIBIA("Namíbia", "NAM", "+264"),
    NAURU("Nauru", "NRU", "+674"),
    NEPAL("Nepal", "NPL", "+977"),
    NICARAGUA("Nicarágua", "NIC", "+505"),
    NIGER("Níger", "NER", "+227"),
    NIGERIA("Nigéria", "NGA", "+234"),
    NORUEGA("Noruega", "NOR", "+47"),
    NOVA_ZELANDIA("Nova Zelândia", "NZL", "+64"),
    OMA("Omã", "OMN", "+968"),
    PALAU("Palau", "PLW", "+680"),
    PANAMA("Panamá", "PAN", "+507"),
    PAPUA_NOVA_GUINE("Papua Nova Guiné", "PNG", "+675"),
    PAQUISTAO("Paquistão", "PAK", "+92"),
    PARAGUAI("Paraguai", "PRY", "+595"),
    PERU("Peru", "PER", "+51"),
    POLONIA("Polônia", "POL", "+48"),
    PORTUGAL("Portugal", "PRT", "+351"),
    QUENIA("Quênia", "KEN", "+254"),
    QUIRGUISTAO("Quirguistão", "KGZ", "+996"),
    REINO_UNIDO("Reino Unido", "GBR", "+44"),
    REPUBLICA_CENTRO_AFRICANA("República Centro-Africana", "CAF", "+236"),
    REPUBLICA_CHECA("República Checa", "CZE", "+420"),
    REPUBLICA_DOMINICANA("República Dominicana", "DOM", "+1-809, +1-829, +1-849"),
    ROMENIA("Romênia", "ROU", "+40"),
    RUANDA("Ruanda", "RWA", "+250"),
    RUSSIA("Rússia", "RUS", "+7"),
    SAMOA("Samoa", "WSM", "+685"),
    SAN_MARINO("San Marino", "SMR", "+378"),
    SANTA_LUCIA("Santa Lúcia", "LCA", "+1-758"),
    SAO_CISTOVAO_E_NEVIS("São Cristóvão e Nevis", "KNA", "+1-869"),
    SAO_TOME_E_PRINCIPE("São Tomé e Príncipe", "STP", "+239"),
    SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas", "VCT", "+1-784"),
    SENEGAL("Senegal", "SEN", "+221"),
    SERRA_LEOA("Serra Leoa", "SLE", "+232"),
    SERVIA("Sérvia", "SRB", "+381"),
    SEYCHELLES("Seychelles", "SYC", "+248"),
    SINGAPURA("Singapura", "SGP", "+65"),
    SIRIA("Síria", "SYR", "+963"),
    SOMALIA("Somália", "SOM", "+252"),
    SRI_LANKA("Sri Lanka", "LKA", "+94"),
    SUAZILANDIA("Suazilândia", "SWZ", "+268"),
    SUDAO("Sudão", "SDN", "+249"),
    SUDAO_DO_SUL("Sudão do Sul", "SSD", "+211"),
    SUECIA("Suécia", "SWE", "+46"),
    SUICA("Suíça", "CHE", "+41"),
    SURINAME("Suriname", "SUR", "+597"),
    TAILANDIA("Tailândia", "THA", "+66"),
    TAIWAN("Taiwan", "TWN", "+886"),
    TAJIQUISTAO("Tajiquistão", "TJK", "+992"),
    TANZANIA("Tanzânia", "TZA", "+255"),
    TIMOR_LESTE("Timor Leste", "TLS", "+670"),
    TOGO("Togo", "TGO", "+228"),
    TONGA("Tonga", "TON", "+676"),
    TRINIDAD_E_TOBAGO("Trinidad e Tobago", "TTO", "+1-868"),
    TUNISIA("Tunísia", "TUN", "+216"),
    TURCOMENISTAO("Turcomenistão", "TKM", "+993"),
    TURQUIA("Turquia", "TUR", "+90"),
    TUVALU("Tuvalu", "TUV", "+688"),
    UCRANIA("Ucrânia", "UKR", "+380"),
    UGANDA("Uganda", "UGA", "+256"),
    URUGUAI("Uruguai", "URY", "+598"),
    UZBEQUISTAO("Uzbequistão", "UZB", "+998"),
    VANUATU("Vanuatu", "VUT", "+678"),
    VATICANO("Vaticano", "VAT", "+39-06, +379"),
    VENEZUELA("Venezuela", "VEN", "+58"),
    VIETNA("Vietnã", "VNM", "+84"),
    ZAMBIA("Zâmbia", "ZMB", "+260"),
    ZIMBABUE("Zimbábue", "ZWE", "+263");

    private String nome;
    private String nomeTresDigitos;
    private String ddi;

    @JsonCreator
    public static Paises consultarPorNomeOuDdi(String nome, String ddi) {
        return matchByPredicate(p -> normalize(p.nome).equals(normalize(nome))).or(
                () -> matchByPredicate(p -> p.ddi.equals(ddi))).orElseThrow(
                () -> new RuntimeException(MessageFormat.format("País {0} não encontrado", nome)));
    }

    private static Optional<Paises> matchByPredicate(Predicate<Paises> predicate) {
        return Stream.of(values()).filter(predicate).findFirst();
    }

    private static String normalize(String s) {
        return Normalizer.normalize(s, Normalizer.Form.NFD).replaceAll("\\{InCombiningDiacriticalMarks}+",
                "").toLowerCase();
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", Paises.class.getSimpleName() + "[", "]").add("nome='" + nome + "'").add(
                "nomeTresDigitos='" + nomeTresDigitos + "'").add("ddi='" + ddi + "'").toString();
    }
}
